-- Repariert/erstellt auth.users + auth.identities für alle Profile
-- Idempotent: kann mehrfach ausgeführt werden

-- Anna Schneider (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '30940837-1e91-41a4-965a-5db84ee35782', 'authenticated', 'authenticated', 'anna.schneider@klassenhub.local', crypt('anna123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '30940837-1e91-41a4-965a-5db84ee35782', '30940837-1e91-41a4-965a-5db84ee35782', jsonb_build_object('sub', '30940837-1e91-41a4-965a-5db84ee35782', 'email', 'anna.schneider@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Ben Lehner (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'bf4bb987-548a-4d3d-85e3-27c9f9c02cdc', 'authenticated', 'authenticated', 'ben.lehner@klassenhub.local', crypt('ben123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'bf4bb987-548a-4d3d-85e3-27c9f9c02cdc', 'bf4bb987-548a-4d3d-85e3-27c9f9c02cdc', jsonb_build_object('sub', 'bf4bb987-548a-4d3d-85e3-27c9f9c02cdc', 'email', 'ben.lehner@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- David Moser (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '0da47605-ad63-41d2-989e-d71a5e55f0da', 'authenticated', 'authenticated', 'david.moser@klassenhub.local', crypt('david123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '0da47605-ad63-41d2-989e-d71a5e55f0da', '0da47605-ad63-41d2-989e-d71a5e55f0da', jsonb_build_object('sub', '0da47605-ad63-41d2-989e-d71a5e55f0da', 'email', 'david.moser@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Emma Koch (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'bc28a964-b408-478c-bfa9-63f2233d1d42', 'authenticated', 'authenticated', 'emma.koch@klassenhub.local', crypt('emma123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'bc28a964-b408-478c-bfa9-63f2233d1d42', 'bc28a964-b408-478c-bfa9-63f2233d1d42', jsonb_build_object('sub', 'bc28a964-b408-478c-bfa9-63f2233d1d42', 'email', 'emma.koch@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Bauer (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'e022dee4-44f3-48a3-a21c-060d3ddbb155', 'authenticated', 'authenticated', 'eltern.bauer@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'e022dee4-44f3-48a3-a21c-060d3ddbb155', 'e022dee4-44f3-48a3-a21c-060d3ddbb155', jsonb_build_object('sub', 'e022dee4-44f3-48a3-a21c-060d3ddbb155', 'email', 'eltern.bauer@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Fischer (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'b581f38c-e3a3-49a0-ae52-6f3565dca889', 'authenticated', 'authenticated', 'eltern.fischer@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'b581f38c-e3a3-49a0-ae52-6f3565dca889', 'b581f38c-e3a3-49a0-ae52-6f3565dca889', jsonb_build_object('sub', 'b581f38c-e3a3-49a0-ae52-6f3565dca889', 'email', 'eltern.fischer@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Gruber (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '73f174a1-985d-4904-bdac-536ae4902f63', 'authenticated', 'authenticated', 'eltern.gruber@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '73f174a1-985d-4904-bdac-536ae4902f63', '73f174a1-985d-4904-bdac-536ae4902f63', jsonb_build_object('sub', '73f174a1-985d-4904-bdac-536ae4902f63', 'email', 'eltern.gruber@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Hofer (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'f8a95f87-dae6-4ca9-8b6a-99397d8aaa79', 'authenticated', 'authenticated', 'eltern.hofer@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'f8a95f87-dae6-4ca9-8b6a-99397d8aaa79', 'f8a95f87-dae6-4ca9-8b6a-99397d8aaa79', jsonb_build_object('sub', 'f8a95f87-dae6-4ca9-8b6a-99397d8aaa79', 'email', 'eltern.hofer@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Huber (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '23af76b8-5880-4d01-ba7a-6d3f658bf6bd', 'authenticated', 'authenticated', 'eltern.huber@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '23af76b8-5880-4d01-ba7a-6d3f658bf6bd', '23af76b8-5880-4d01-ba7a-6d3f658bf6bd', jsonb_build_object('sub', '23af76b8-5880-4d01-ba7a-6d3f658bf6bd', 'email', 'eltern.huber@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Koch (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'd2e487c2-f872-4576-8bf1-2436df093f37', 'authenticated', 'authenticated', 'eltern.koch@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'd2e487c2-f872-4576-8bf1-2436df093f37', 'd2e487c2-f872-4576-8bf1-2436df093f37', jsonb_build_object('sub', 'd2e487c2-f872-4576-8bf1-2436df093f37', 'email', 'eltern.koch@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Lehner (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'b3d55fe3-84d1-476c-b1ba-edbc42442a16', 'authenticated', 'authenticated', 'eltern.lehner@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'b3d55fe3-84d1-476c-b1ba-edbc42442a16', 'b3d55fe3-84d1-476c-b1ba-edbc42442a16', jsonb_build_object('sub', 'b3d55fe3-84d1-476c-b1ba-edbc42442a16', 'email', 'eltern.lehner@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Maier (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '7939664f-c58c-48f9-a78f-8c7015f5d1c6', 'authenticated', 'authenticated', 'eltern.maier@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '7939664f-c58c-48f9-a78f-8c7015f5d1c6', '7939664f-c58c-48f9-a78f-8c7015f5d1c6', jsonb_build_object('sub', '7939664f-c58c-48f9-a78f-8c7015f5d1c6', 'email', 'eltern.maier@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Moser (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '30b190f6-dfb3-44f5-b113-327a1986df62', 'authenticated', 'authenticated', 'eltern.moser@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '30b190f6-dfb3-44f5-b113-327a1986df62', '30b190f6-dfb3-44f5-b113-327a1986df62', jsonb_build_object('sub', '30b190f6-dfb3-44f5-b113-327a1986df62', 'email', 'eltern.moser@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Müller (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '965c677c-807b-4d8d-932b-1681d3a949be', 'authenticated', 'authenticated', 'eltern.mueller@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '965c677c-807b-4d8d-932b-1681d3a949be', '965c677c-807b-4d8d-932b-1681d3a949be', jsonb_build_object('sub', '965c677c-807b-4d8d-932b-1681d3a949be', 'email', 'eltern.mueller@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Pichler (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '87b567cf-6792-43cf-89ef-5bd36a2f4985', 'authenticated', 'authenticated', 'eltern.pichler@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '87b567cf-6792-43cf-89ef-5bd36a2f4985', '87b567cf-6792-43cf-89ef-5bd36a2f4985', jsonb_build_object('sub', '87b567cf-6792-43cf-89ef-5bd36a2f4985', 'email', 'eltern.pichler@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Schneider (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '4261343b-836d-4b6f-b134-bf30dac9cd12', 'authenticated', 'authenticated', 'eltern.schneider@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '4261343b-836d-4b6f-b134-bf30dac9cd12', '4261343b-836d-4b6f-b134-bf30dac9cd12', jsonb_build_object('sub', '4261343b-836d-4b6f-b134-bf30dac9cd12', 'email', 'eltern.schneider@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Steiner (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '2b69584e-7fce-46d1-828d-045e94027645', 'authenticated', 'authenticated', 'eltern.steiner@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '2b69584e-7fce-46d1-828d-045e94027645', '2b69584e-7fce-46d1-828d-045e94027645', jsonb_build_object('sub', '2b69584e-7fce-46d1-828d-045e94027645', 'email', 'eltern.steiner@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Wagner (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '9ae77cfa-7f01-4ba9-9f8f-001c5bf1c79c', 'authenticated', 'authenticated', 'eltern.wagner@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '9ae77cfa-7f01-4ba9-9f8f-001c5bf1c79c', '9ae77cfa-7f01-4ba9-9f8f-001c5bf1c79c', jsonb_build_object('sub', '9ae77cfa-7f01-4ba9-9f8f-001c5bf1c79c', 'email', 'eltern.wagner@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Fam. Weber (parent)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'a6b42a97-5d98-4591-ad47-b98b0c458460', 'authenticated', 'authenticated', 'eltern.weber@klassenhub.local', crypt('eltern123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'a6b42a97-5d98-4591-ad47-b98b0c458460', 'a6b42a97-5d98-4591-ad47-b98b0c458460', jsonb_build_object('sub', 'a6b42a97-5d98-4591-ad47-b98b0c458460', 'email', 'eltern.weber@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Felix Wagner (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '284e3f3a-401c-40c9-9190-a9777d4bdce1', 'authenticated', 'authenticated', 'felix.wagner@klassenhub.local', crypt('felix123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '284e3f3a-401c-40c9-9190-a9777d4bdce1', '284e3f3a-401c-40c9-9190-a9777d4bdce1', jsonb_build_object('sub', '284e3f3a-401c-40c9-9190-a9777d4bdce1', 'email', 'felix.wagner@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Herr Berger (teacher)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'f98b22ad-f913-48e7-8701-4f244f014048', 'authenticated', 'authenticated', 'admin@klassenhub.local', crypt('admin1', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'f98b22ad-f913-48e7-8701-4f244f014048', 'f98b22ad-f913-48e7-8701-4f244f014048', jsonb_build_object('sub', 'f98b22ad-f913-48e7-8701-4f244f014048', 'email', 'admin@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Jonas Gruber (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '51a6560e-25a9-4bbe-a0da-12be8ebabd9d', 'authenticated', 'authenticated', 'jonas.gruber@klassenhub.local', crypt('jonas123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '51a6560e-25a9-4bbe-a0da-12be8ebabd9d', '51a6560e-25a9-4bbe-a0da-12be8ebabd9d', jsonb_build_object('sub', '51a6560e-25a9-4bbe-a0da-12be8ebabd9d', 'email', 'jonas.gruber@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Julia Maier (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '47eaad61-ab94-40e5-878d-ea8d6f9160a5', 'authenticated', 'authenticated', 'julia.maier@klassenhub.local', crypt('julia123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '47eaad61-ab94-40e5-878d-ea8d6f9160a5', '47eaad61-ab94-40e5-878d-ea8d6f9160a5', jsonb_build_object('sub', '47eaad61-ab94-40e5-878d-ea8d6f9160a5', 'email', 'julia.maier@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Lea Pichler (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'fac9c4db-fcc7-4ede-9103-7afa3d770b3b', 'authenticated', 'authenticated', 'lea.pichler@klassenhub.local', crypt('lea123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'fac9c4db-fcc7-4ede-9103-7afa3d770b3b', 'fac9c4db-fcc7-4ede-9103-7afa3d770b3b', jsonb_build_object('sub', 'fac9c4db-fcc7-4ede-9103-7afa3d770b3b', 'email', 'lea.pichler@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Lena Hofer (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'dc3bba45-54c3-4f1f-affe-246c7a6fd150', 'authenticated', 'authenticated', 'lena.hofer@klassenhub.local', crypt('lena123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'dc3bba45-54c3-4f1f-affe-246c7a6fd150', 'dc3bba45-54c3-4f1f-affe-246c7a6fd150', jsonb_build_object('sub', 'dc3bba45-54c3-4f1f-affe-246c7a6fd150', 'email', 'lena.hofer@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Lukas Fischer (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '877ad5ad-7a7e-4130-aa13-fbf09e23d24c', 'authenticated', 'authenticated', 'lukas.fischer@klassenhub.local', crypt('lukas123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '877ad5ad-7a7e-4130-aa13-fbf09e23d24c', '877ad5ad-7a7e-4130-aa13-fbf09e23d24c', jsonb_build_object('sub', '877ad5ad-7a7e-4130-aa13-fbf09e23d24c', 'email', 'lukas.fischer@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Max Bauer (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'd3b3c956-9101-4294-b8b0-142f3c62a242', 'authenticated', 'authenticated', 'max.bauer@klassenhub.local', crypt('max123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'd3b3c956-9101-4294-b8b0-142f3c62a242', 'd3b3c956-9101-4294-b8b0-142f3c62a242', jsonb_build_object('sub', 'd3b3c956-9101-4294-b8b0-142f3c62a242', 'email', 'max.bauer@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Mia Huber (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '35b5dca8-ef63-4d75-95a3-7033a2c1eb69', 'authenticated', 'authenticated', 'mia.huber@klassenhub.local', crypt('mia123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '35b5dca8-ef63-4d75-95a3-7033a2c1eb69', '35b5dca8-ef63-4d75-95a3-7033a2c1eb69', jsonb_build_object('sub', '35b5dca8-ef63-4d75-95a3-7033a2c1eb69', 'email', 'mia.huber@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Noah Weber (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'd5f487f6-52dc-4542-8fe6-37f44a16174a', 'authenticated', 'authenticated', 'noah.weber@klassenhub.local', crypt('noah123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'd5f487f6-52dc-4542-8fe6-37f44a16174a', 'd5f487f6-52dc-4542-8fe6-37f44a16174a', jsonb_build_object('sub', 'd5f487f6-52dc-4542-8fe6-37f44a16174a', 'email', 'noah.weber@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Sophie Müller (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', '681b0999-673b-43e0-a8a0-95b6b6c5ecc8', 'authenticated', 'authenticated', 'sophie.mueller@klassenhub.local', crypt('sophie123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), '681b0999-673b-43e0-a8a0-95b6b6c5ecc8', '681b0999-673b-43e0-a8a0-95b6b6c5ecc8', jsonb_build_object('sub', '681b0999-673b-43e0-a8a0-95b6b6c5ecc8', 'email', 'sophie.mueller@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

-- Tim Steiner (student)
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone_change, phone_change_token, reauthentication_token)
VALUES ('00000000-0000-0000-0000-000000000000', 'fdba5103-a038-4d7f-900e-f75d61a31d0f', 'authenticated', 'authenticated', 'tim.steiner@klassenhub.local', crypt('tim123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', '', '', '', '', '', '', '', '')
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, encrypted_password = EXCLUDED.encrypted_password, email_confirmed_at = now(), updated_at = now(), confirmation_token = COALESCE(NULLIF(auth.users.confirmation_token, NULL), ''), recovery_token = COALESCE(auth.users.recovery_token, ''), email_change = COALESCE(auth.users.email_change, ''), email_change_token_new = COALESCE(auth.users.email_change_token_new, ''), email_change_token_current = COALESCE(auth.users.email_change_token_current, ''), phone_change = COALESCE(auth.users.phone_change, ''), phone_change_token = COALESCE(auth.users.phone_change_token, ''), reauthentication_token = COALESCE(auth.users.reauthentication_token, '');
INSERT INTO auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
VALUES (gen_random_uuid(), 'fdba5103-a038-4d7f-900e-f75d61a31d0f', 'fdba5103-a038-4d7f-900e-f75d61a31d0f', jsonb_build_object('sub', 'fdba5103-a038-4d7f-900e-f75d61a31d0f', 'email', 'tim.steiner@klassenhub.local', 'email_verified', false, 'phone_verified', false), 'email', now(), now(), now())
ON CONFLICT (provider_id, provider) DO UPDATE SET identity_data = EXCLUDED.identity_data, updated_at = now();

