export const SUBJECTS = [
  { label: 'Mathematik',            short: 'M',      color: '#0F8A82' },
  { label: 'Deutsch',               short: 'D',      color: '#B0413E' },
  { label: 'Englisch',              short: 'E',      color: '#2F6DB0' },
  { label: 'Biologie',              short: 'BU',     color: '#10B981' },
  { label: 'Geografie',             short: 'GW',     color: '#C98A2B' },
  { label: 'Geschichte',            short: 'GS',     color: '#7B5EA7' },
  { label: 'Physik',                short: 'PH',     color: '#0369A1' },
  { label: 'Chemie',                short: 'CH',     color: '#9D174D' },
  { label: 'Musik',                 short: 'MU',     color: '#D44B9E' },
  { label: 'Bew. & Sport',          short: 'BSP',    color: '#E07B35' },
  { label: 'Digitale Grundbildung', short: 'DGB',    color: '#6366F1' },
  { label: 'Berufsorientierung',    short: 'BO',     color: '#64748B' },
  { label: 'Sonstiges',             short: 'Sonst.', color: '#6E7E80' },
]
